import {
  ShoppingCart,
  Coffee,
  Home,
  Car,
  Utensils,
  Heart,
  Tag,
  Gift,
  Briefcase,
  Zap,
  Plane,
  Activity,
  Dumbbell,
  Book,
  Music,
  Film,
  Gamepad2,
  Camera,
  Palette,
  Languages,
  Dog,
  GraduationCap,
  Pill,
  Stethoscope,
  Baby,
  Users,
  HeartPulse,
  Smartphone,
  Laptop,
  Tv,
  Ghost,
  Rocket,
  Wallet,
  DollarSign,
  PiggyBank,
  Store,
  Trash2,
  Brush,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const categoryIconMap: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  coffee: Coffee,
  home: Home,
  car: Car,
  utensils: Utensils,
  heart: Heart,
  tag: Tag,
  gift: Gift,
  briefcase: Briefcase,
  zap: Zap,
  plane: Plane,
  activity: Activity,
  dumbbell: Dumbbell,
  book: Book,
  music: Music,
  film: Film,
  gamepad: Gamepad2,
  camera: Camera,
  palette: Palette,
  languages: Languages,
  dog: Dog,
  graduation: GraduationCap,
  pill: Pill,
  stethoscope: Stethoscope,
  baby: Baby,
  users: Users,
  "heart-pulse": HeartPulse,
  smartphone: Smartphone,
  laptop: Laptop,
  tv: Tv,
  ghost: Ghost,
  rocket: Rocket,
  wallet: Wallet,
  dollar: DollarSign,
  piggy: PiggyBank,
  store: Store,
  trash: Trash2,
  brush: Brush,
};

export const categoryIconOptions = [
  "shopping-cart",
  "coffee",
  "home",
  "car",
  "utensils",
  "heart",
  "tag",
  "gift",
  "briefcase",
  "zap",
  "plane",
  "activity",
  "dumbbell",
  "book",
  "music",
  "film",
  "gamepad",
  "camera",
  "palette",
  "languages",
  "dog",
  "graduation",
  "pill",
  "stethoscope",
  "baby",
  "users",
  "heart-pulse",
  "smartphone",
  "laptop",
  "tv",
  "ghost",
  "rocket",
  "wallet",
  "dollar",
  "piggy",
  "store",
  "trash",
  "brush",
] as const;

export const getCategoryIcon = (icon: string | null | undefined): LucideIcon =>
  categoryIconMap[icon || "tag"] || Tag;
